// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLhOeDjCWqhEwwjcxc5uTrb7o5ibtozI',
    appId: '1:663572642581:web:570d1464338d89744a871c',
    messagingSenderId: '663572642581',
    projectId: 'rubrick-5a2b8',
    authDomain: 'rubrick-5a2b8.firebaseapp.com',
    storageBucket: 'rubrick-5a2b8.appspot.com',
    measurementId: 'G-GPDSZSF5J1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0c9433ls4W6M9K4ZcLeNLSRN82q2WrXs',
    appId: '1:663572642581:android:40dcde31dc7806af4a871c',
    messagingSenderId: '663572642581',
    projectId: 'rubrick-5a2b8',
    storageBucket: 'rubrick-5a2b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe0kRFbVL9wn4hFx4_-D31cYTdng8jcF8',
    appId: '1:663572642581:ios:2fe5571fcb396a7a4a871c',
    messagingSenderId: '663572642581',
    projectId: 'rubrick-5a2b8',
    storageBucket: 'rubrick-5a2b8.appspot.com',
    iosClientId: '663572642581-go41k5l5hkm66tb4pafgennqc2pqs5nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.rubrick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe0kRFbVL9wn4hFx4_-D31cYTdng8jcF8',
    appId: '1:663572642581:ios:2fe5571fcb396a7a4a871c',
    messagingSenderId: '663572642581',
    projectId: 'rubrick-5a2b8',
    storageBucket: 'rubrick-5a2b8.appspot.com',
    iosClientId: '663572642581-go41k5l5hkm66tb4pafgennqc2pqs5nk.apps.googleusercontent.com',
    iosBundleId: 'com.example.rubrick',
  );
}
